name: PHP CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Syntax Check (lint)
        run: |
          find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Start PHP Server
        run: php -S localhost:8000 -t .
        background: true

      - name: Wait for server
        run: sleep 3

      - name: Run Custom Tests
        run: php tests/test_all.php
